#ifndef CITY_WEATHER_H
#define CITY_WEATHER_H

#pragma warning(disable: 4103)
#pragma pack(1)

#include "data_types.h"
#include "weather.h"

class CityWeather
{
private:
    int CityWeatherID;                          // ID of the city (auto generated by editor)
    char CityWeatherName[ SHORT_TEXT_LENGTH ];  // Name of the city which is modelled (editable)
    WEATHER_SEASON CityWeatherSeason[ 4 ];      // Seasonal model for this city (editable)
    WEATHER_CONDITION CityWeatherCondition;     // Current Weather in this city (not editable)

public:
    CityWeather();
};

#endif // CITY_WEATHER_H
